### PR TITLE
feat!: update implementation for vue 3

### PR DESCRIPTION
**Pull request by danielroe**
resolves https://github.com/danielroe/stream-vue/issues/83

## Summary by CodeRabbit

- **New Features**
  - Introduced a new video stream management functionality in the Vue.js application.

- **Improvements**
  - Upgraded Vue.js dependencies to support the latest version (Vue 3).
  - Refactored components to use the Composition API for better reactivity and simplicity.
  - Enhanced the type definitions for better flexibility in props.

- **Bug Fixes**
  - Updated test configurations to be compatible with the latest Vue.js version.

- **Development Enhancements**
  - Added Vite configuration for improved development and build processes.
  - Updated development dependencies to their latest versions.

### CODE REVIEW

**Comment by fenn1ks** [comment]
thanks for the work done! but will there be a version update on npm? I have a problem when trying to install
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: project@undefined
npm ERR! Found: vue@3.4.27
npm ERR! node_modules/vue
npm ERR!   vue@"^3.4.27" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer vue@"^2.6.0" from stream-vue@0.4.0
npm ERR! node_modules/stream-vue
npm ERR!   stream-vue@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by danielroe** [comment]
I do - thanks for the ping.

**Comment by danielroe** [comment]
This is now released as v0.5.0. Please let me know of any issues you experience.

**Comment by fenn1ks** [comment]
> This is now released as v0.5.0. Please let me know of any issues you experience.


It works fine! Thank you very much for your work!

**Pull request merged**
